### ISSUE TITLE
SVG transform (translate) is not taken into account (node converter) which leads to glitches

### ISSUE THREAD

**Issue by Th3S4mur41** [L2jLiga/grunt-webfonts#8]
See for instance
![image](https://user-images.githubusercontent.com/5543595/47296745-7e826e80-d613-11e8-9959-04513cb01547.png)

The vertical line on the icon should actually go from top right to bottom left.
See following icons for some original SVG, that are fine as is, but have glitches when added to the font with node.
[glitches.zip](https://github.com/L2jLiga/grunt-webfonts/files/2501637/glitches.zip)

Looks like the transform (translate) operation on rect is not being taken into account

**Comment by L2jLiga** [comment]
@Th3S4mur41 is it reproducible only on latest version or on previous too?

**Comment by Th3S4mur41** [comment]
Indeed with 1.0.10, some icons were ok... Other were already showing problems, but slightly different...
With 1.1.2, all icons show the same issue: the strikethrough horizontal.

With 1.0.10, the icon above is fine. But svg-icon-general-video-on from the zip above has a whole different glitch
![image](https://user-images.githubusercontent.com/5543595/47553214-be44a100-d906-11e8-9d09-6bf797200259.png)

**Comment by L2jLiga** [comment]
Okey, then I need to go dipper into [svgo](https://www.npmjs.com/package/svgo) and [element-to-path](https://www.npmjs.com/package/) packages and try to understand why it happens..

In my vision problem should gone if you will transform your svg's shapes into compound path, because while svg font generating [svgicons2svgfont](https://www.npmjs.com/package/svgicons2svgfont) transform they to path

**Comment by Th3S4mur41** [comment]
@L2jLiga any progress on this?

**Comment by L2jLiga** [comment]
v1.1.4 released
